### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by fgregg** [UrbanInstitute/ipeds-scraper#1]
Hi @hrecht, this looks really useful! Would you mind adding a license to this repo. 

If it could be the [MIT license](https://opensource.org/licenses/MIT), that would be super!

**Comment by hrecht** [comment]
Thanks @fgregg! Deferring to @bchartoff as I'm no longer at Urban.
Please chime in at https://github.com/usedgov/API-Program/issues/1, so someday this scraper becomes unnecessary!

**Comment by bchartoff** [comment]
Sure thing, I agree MIT license makes sense for this scraper.

Closed by e425b13bfea343a53b2efa3f996475f3505db7ed

**Comment by fgregg** [comment]
Thanks!
